SELECT F.FLAVOR
FROM FIRST_HALF F, ICECREAM_INFO I
WHERE 
    F.FLAVOR = I.FLAVOR AND
    I.INGREDIENT_TYPE = 'fruit_based'
GROUP BY
    F.FLAVOR
HAVING
    SUM(TOTAL_ORDER) >= 3000
ORDER BY
    SUM(TOTAL_ORDER) DESC